language: android
jdk: oraclejdk8
os: linux
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-23
    - SDK Patch Applier v4
    - Android Support Repository
    - Google Repository